storage:
  endpoint_url: http://swfs-s3.outergods.lan
  bucket: buckets

scan:
  audio_extensions:
    - .flac
    - .mp3
    - .ogg
    - .wav
    - .m4a
    - .aiff
  soundtrack_keywords:
    - "OST"
    - "Soundtrack"
    - "Sound Track"
    - "Original Sound"
    - "Music Pack"
    - "Digital Soundtrack"
    - "Original Score"
  min_audio_files: 1

mode:
  dry_run: false
  upload_audio_files: true
