version: "3.9"

services:
  worker:
    build: .
    image: sst-worker
    container_name: sst-worker
    volumes:
      - /mnt/work_area:/mnt/work_area
    env_file:
      - .env
    environment:
      - PREFECT_API_URL=${PREFECT_API_URL}
    restart: unless-stopped
